/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpacesIndexRouteImport } from './routes/spaces/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as SpacesIdRouteImport } from './routes/spaces/$id'
import { Route as OauthApproveRouteImport } from './routes/oauth/approve'
import { Route as DocsSlugRouteImport } from './routes/docs/$slug'
import { Route as AdminSpendRouteImport } from './routes/admin/spend'
import { Route as SpacesIdIndexRouteImport } from './routes/spaces/$id/index'
import { Route as SpacesIdProductionRouteImport } from './routes/spaces/$id/production'
import { Route as SpacesIdAssetsAssetIdRouteImport } from './routes/spaces/$id/assets/$assetId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesIndexRoute = SpacesIndexRouteImport.update({
  id: '/spaces/',
  path: '/spaces/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const SpacesIdRoute = SpacesIdRouteImport.update({
  id: '/spaces/$id',
  path: '/spaces/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthApproveRoute = OauthApproveRouteImport.update({
  id: '/oauth/approve',
  path: '/oauth/approve',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsRoute,
} as any)
const AdminSpendRoute = AdminSpendRouteImport.update({
  id: '/admin/spend',
  path: '/admin/spend',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesIdIndexRoute = SpacesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpacesIdRoute,
} as any)
const SpacesIdProductionRoute = SpacesIdProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => SpacesIdRoute,
} as any)
const SpacesIdAssetsAssetIdRoute = SpacesIdAssetsAssetIdRouteImport.update({
  id: '/assets/$assetId',
  path: '/assets/$assetId',
  getParentRoute: () => SpacesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/admin/spend': typeof AdminSpendRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/oauth/approve': typeof OauthApproveRoute
  '/spaces/$id': typeof SpacesIdRouteWithChildren
  '/docs/': typeof DocsIndexRoute
  '/spaces/': typeof SpacesIndexRoute
  '/spaces/$id/production': typeof SpacesIdProductionRoute
  '/spaces/$id/': typeof SpacesIdIndexRoute
  '/spaces/$id/assets/$assetId': typeof SpacesIdAssetsAssetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/admin/spend': typeof AdminSpendRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/oauth/approve': typeof OauthApproveRoute
  '/docs': typeof DocsIndexRoute
  '/spaces': typeof SpacesIndexRoute
  '/spaces/$id/production': typeof SpacesIdProductionRoute
  '/spaces/$id': typeof SpacesIdIndexRoute
  '/spaces/$id/assets/$assetId': typeof SpacesIdAssetsAssetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/admin/spend': typeof AdminSpendRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/oauth/approve': typeof OauthApproveRoute
  '/spaces/$id': typeof SpacesIdRouteWithChildren
  '/docs/': typeof DocsIndexRoute
  '/spaces/': typeof SpacesIndexRoute
  '/spaces/$id/production': typeof SpacesIdProductionRoute
  '/spaces/$id/': typeof SpacesIdIndexRoute
  '/spaces/$id/assets/$assetId': typeof SpacesIdAssetsAssetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/dashboard'
    | '/docs'
    | '/login'
    | '/pricing'
    | '/profile'
    | '/admin/spend'
    | '/docs/$slug'
    | '/oauth/approve'
    | '/spaces/$id'
    | '/docs/'
    | '/spaces/'
    | '/spaces/$id/production'
    | '/spaces/$id/'
    | '/spaces/$id/assets/$assetId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/dashboard'
    | '/login'
    | '/pricing'
    | '/profile'
    | '/admin/spend'
    | '/docs/$slug'
    | '/oauth/approve'
    | '/docs'
    | '/spaces'
    | '/spaces/$id/production'
    | '/spaces/$id'
    | '/spaces/$id/assets/$assetId'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/dashboard'
    | '/docs'
    | '/login'
    | '/pricing'
    | '/profile'
    | '/admin/spend'
    | '/docs/$slug'
    | '/oauth/approve'
    | '/spaces/$id'
    | '/docs/'
    | '/spaces/'
    | '/spaces/$id/production'
    | '/spaces/$id/'
    | '/spaces/$id/assets/$assetId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  DashboardRoute: typeof DashboardRoute
  DocsRoute: typeof DocsRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  AdminSpendRoute: typeof AdminSpendRoute
  OauthApproveRoute: typeof OauthApproveRoute
  SpacesIdRoute: typeof SpacesIdRouteWithChildren
  SpacesIndexRoute: typeof SpacesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/': {
      id: '/spaces/'
      path: '/spaces'
      fullPath: '/spaces/'
      preLoaderRoute: typeof SpacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/spaces/$id': {
      id: '/spaces/$id'
      path: '/spaces/$id'
      fullPath: '/spaces/$id'
      preLoaderRoute: typeof SpacesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/approve': {
      id: '/oauth/approve'
      path: '/oauth/approve'
      fullPath: '/oauth/approve'
      preLoaderRoute: typeof OauthApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof DocsRoute
    }
    '/admin/spend': {
      id: '/admin/spend'
      path: '/admin/spend'
      fullPath: '/admin/spend'
      preLoaderRoute: typeof AdminSpendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/$id/': {
      id: '/spaces/$id/'
      path: '/'
      fullPath: '/spaces/$id/'
      preLoaderRoute: typeof SpacesIdIndexRouteImport
      parentRoute: typeof SpacesIdRoute
    }
    '/spaces/$id/production': {
      id: '/spaces/$id/production'
      path: '/production'
      fullPath: '/spaces/$id/production'
      preLoaderRoute: typeof SpacesIdProductionRouteImport
      parentRoute: typeof SpacesIdRoute
    }
    '/spaces/$id/assets/$assetId': {
      id: '/spaces/$id/assets/$assetId'
      path: '/assets/$assetId'
      fullPath: '/spaces/$id/assets/$assetId'
      preLoaderRoute: typeof SpacesIdAssetsAssetIdRouteImport
      parentRoute: typeof SpacesIdRoute
    }
  }
}

interface DocsRouteChildren {
  DocsSlugRoute: typeof DocsSlugRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSlugRoute: DocsSlugRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface SpacesIdRouteChildren {
  SpacesIdProductionRoute: typeof SpacesIdProductionRoute
  SpacesIdIndexRoute: typeof SpacesIdIndexRoute
  SpacesIdAssetsAssetIdRoute: typeof SpacesIdAssetsAssetIdRoute
}

const SpacesIdRouteChildren: SpacesIdRouteChildren = {
  SpacesIdProductionRoute: SpacesIdProductionRoute,
  SpacesIdIndexRoute: SpacesIdIndexRoute,
  SpacesIdAssetsAssetIdRoute: SpacesIdAssetsAssetIdRoute,
}

const SpacesIdRouteWithChildren = SpacesIdRoute._addFileChildren(
  SpacesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  DashboardRoute: DashboardRoute,
  DocsRoute: DocsRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  AdminSpendRoute: AdminSpendRoute,
  OauthApproveRoute: OauthApproveRoute,
  SpacesIdRoute: SpacesIdRouteWithChildren,
  SpacesIndexRoute: SpacesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
