/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpacesIndexRouteImport } from './routes/spaces/index'
import { Route as SpacesIdRouteImport } from './routes/spaces/$id'
import { Route as OauthApproveRouteImport } from './routes/oauth/approve'
import { Route as SpacesIdIndexRouteImport } from './routes/spaces/$id/index'
import { Route as SpacesIdProductionRouteImport } from './routes/spaces/$id/production'
import { Route as SpacesIdAssetsAssetIdRouteImport } from './routes/spaces/$id/assets/$assetId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesIndexRoute = SpacesIndexRouteImport.update({
  id: '/spaces/',
  path: '/spaces/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesIdRoute = SpacesIdRouteImport.update({
  id: '/spaces/$id',
  path: '/spaces/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthApproveRoute = OauthApproveRouteImport.update({
  id: '/oauth/approve',
  path: '/oauth/approve',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesIdIndexRoute = SpacesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpacesIdRoute,
} as any)
const SpacesIdProductionRoute = SpacesIdProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => SpacesIdRoute,
} as any)
const SpacesIdAssetsAssetIdRoute = SpacesIdAssetsAssetIdRouteImport.update({
  id: '/assets/$assetId',
  path: '/assets/$assetId',
  getParentRoute: () => SpacesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/oauth/approve': typeof OauthApproveRoute
  '/spaces/$id': typeof SpacesIdRouteWithChildren
  '/spaces/': typeof SpacesIndexRoute
  '/spaces/$id/production': typeof SpacesIdProductionRoute
  '/spaces/$id/': typeof SpacesIdIndexRoute
  '/spaces/$id/assets/$assetId': typeof SpacesIdAssetsAssetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/oauth/approve': typeof OauthApproveRoute
  '/spaces': typeof SpacesIndexRoute
  '/spaces/$id/production': typeof SpacesIdProductionRoute
  '/spaces/$id': typeof SpacesIdIndexRoute
  '/spaces/$id/assets/$assetId': typeof SpacesIdAssetsAssetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/oauth/approve': typeof OauthApproveRoute
  '/spaces/$id': typeof SpacesIdRouteWithChildren
  '/spaces/': typeof SpacesIndexRoute
  '/spaces/$id/production': typeof SpacesIdProductionRoute
  '/spaces/$id/': typeof SpacesIdIndexRoute
  '/spaces/$id/assets/$assetId': typeof SpacesIdAssetsAssetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/oauth/approve'
    | '/spaces/$id'
    | '/spaces/'
    | '/spaces/$id/production'
    | '/spaces/$id/'
    | '/spaces/$id/assets/$assetId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/oauth/approve'
    | '/spaces'
    | '/spaces/$id/production'
    | '/spaces/$id'
    | '/spaces/$id/assets/$assetId'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/oauth/approve'
    | '/spaces/$id'
    | '/spaces/'
    | '/spaces/$id/production'
    | '/spaces/$id/'
    | '/spaces/$id/assets/$assetId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  OauthApproveRoute: typeof OauthApproveRoute
  SpacesIdRoute: typeof SpacesIdRouteWithChildren
  SpacesIndexRoute: typeof SpacesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/': {
      id: '/spaces/'
      path: '/spaces'
      fullPath: '/spaces/'
      preLoaderRoute: typeof SpacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/$id': {
      id: '/spaces/$id'
      path: '/spaces/$id'
      fullPath: '/spaces/$id'
      preLoaderRoute: typeof SpacesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/approve': {
      id: '/oauth/approve'
      path: '/oauth/approve'
      fullPath: '/oauth/approve'
      preLoaderRoute: typeof OauthApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/$id/': {
      id: '/spaces/$id/'
      path: '/'
      fullPath: '/spaces/$id/'
      preLoaderRoute: typeof SpacesIdIndexRouteImport
      parentRoute: typeof SpacesIdRoute
    }
    '/spaces/$id/production': {
      id: '/spaces/$id/production'
      path: '/production'
      fullPath: '/spaces/$id/production'
      preLoaderRoute: typeof SpacesIdProductionRouteImport
      parentRoute: typeof SpacesIdRoute
    }
    '/spaces/$id/assets/$assetId': {
      id: '/spaces/$id/assets/$assetId'
      path: '/assets/$assetId'
      fullPath: '/spaces/$id/assets/$assetId'
      preLoaderRoute: typeof SpacesIdAssetsAssetIdRouteImport
      parentRoute: typeof SpacesIdRoute
    }
  }
}

interface SpacesIdRouteChildren {
  SpacesIdProductionRoute: typeof SpacesIdProductionRoute
  SpacesIdIndexRoute: typeof SpacesIdIndexRoute
  SpacesIdAssetsAssetIdRoute: typeof SpacesIdAssetsAssetIdRoute
}

const SpacesIdRouteChildren: SpacesIdRouteChildren = {
  SpacesIdProductionRoute: SpacesIdProductionRoute,
  SpacesIdIndexRoute: SpacesIdIndexRoute,
  SpacesIdAssetsAssetIdRoute: SpacesIdAssetsAssetIdRoute,
}

const SpacesIdRouteWithChildren = SpacesIdRoute._addFileChildren(
  SpacesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  OauthApproveRoute: OauthApproveRoute,
  SpacesIdRoute: SpacesIdRouteWithChildren,
  SpacesIndexRoute: SpacesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
